evade_always_available: false
evade_chain_delay: 0.1
evade_chain_next: ''
evade_delay_max: 0.0
evade_delay_min: 0.0
evade_hp_max: 60
evade_hp_min: 0
evade_mode: hp_guard
evade_priority: 8
evade_resource_max: 100
evade_resource_min: 0
pot_always_available: false
pot_chain_delay: 0.1
pot_chain_next: ''
pot_delay_max: 0.0
pot_delay_min: 0.0
pot_hp_max: 80
pot_hp_min: 0
pot_mode: hp_guard
pot_priority: 7
pot_resource_max: 100
pot_resource_min: 0
skill1_always_available: false
skill1_chain_delay: 0.1
skill1_chain_next: ''
skill1_delay_max: 0.0
skill1_delay_min: 0.0
skill1_hp_max: 100
skill1_hp_min: 0
skill1_mode: ready
skill1_priority: 3
skill1_resource_max: 100
skill1_resource_min: 0
skill2_always_available: false
skill2_chain_delay: 0.1
skill2_chain_next: ''
skill2_delay_max: 0.0
skill2_delay_min: 0.0
skill2_hp_max: 100
skill2_hp_min: 0
skill2_mode: ready
skill2_priority: 4
skill2_resource_max: 100
skill2_resource_min: 0
skill3_always_available: false
skill3_chain_delay: 0.1
skill3_chain_next: ''
skill3_delay_max: 0.0
skill3_delay_min: 0.0
skill3_hp_max: 100
skill3_hp_min: 0
skill3_mode: ready
skill3_priority: 2
skill3_resource_max: 100
skill3_resource_min: 0
skill4_always_available: false
skill4_chain_delay: 0.1
skill4_chain_next: ''
skill4_delay_max: 0.0
skill4_delay_min: 0.0
skill4_hp_max: 100
skill4_hp_min: 0
skill4_mode: ready
skill4_priority: 1
skill4_resource_max: 100
skill4_resource_min: 0
skill5_always_available: false
skill5_chain_delay: 0.1
skill5_chain_next: ''
skill5_delay_max: 0.0
skill5_delay_min: 0.0
skill5_hp_max: 100
skill5_hp_min: 0
skill5_mode: ready
skill5_priority: 5
skill5_resource_max: 100
skill5_resource_min: 0
skill6: rightclick
skill6_always_available: false
skill6_chain_delay: 0.1
skill6_chain_next: ''
skill6_delay_max: 0.0
skill6_delay_min: 0.0
skill6_enabled: true
skill6_hp_max: 100
skill6_hp_min: 0
skill6_mode: ready
skill6_pos:
- 980
- 45
- 60
- 60
skill6_priority: 6
skill6_resource_max: 100
skill6_resource_min: 0
