evade: space
evade_always_available: false
evade_always_hold: true
evade_cal:
  pixel1_brightness: 152.7
  pixel1_x: 2106
  pixel1_y: 1210
  pixel2_brightness: 152.7
  pixel2_x: 2104
  pixel2_y: 1224
evade_chain_delay: 0.1
evade_chain_next: none
evade_delay_max: 0.0
evade_delay_min: 0.0
evade_enabled: false
evade_hp_max: 60
evade_hp_min: 0
evade_mode: hp_guard
evade_pos:
- 2077
- 1189
- 53
- 60
evade_priority: 8
evade_resource_max: 100
evade_resource_min: 0
pot: q
pot_always_available: false
pot_always_hold: true
pot_cal:
  pixel1_brightness: 152.7
  pixel1_x: 1335
  pixel1_y: 1222
  pixel2_brightness: 152.7
  pixel2_x: 1338
  pixel2_y: 1232
pot_chain_delay: 0.1
pot_chain_next: none
pot_delay_max: 0.0
pot_delay_min: 0.0
pot_enabled: false
pot_hp_max: 60
pot_hp_min: 0
pot_mode: hp_guard
pot_pos:
- 1301
- 1187
- 61
- 60
pot_priority: 7
pot_resource_max: 100
pot_resource_min: 0
skill1: '1'
skill1_always_available: false
skill1_always_hold: true
skill1_cal:
  pixel1_brightness: 173.7
  pixel1_x: 1516
  pixel1_y: 1325
  pixel2_brightness: 225.7
  pixel2_x: 1515
  pixel2_y: 1333
skill1_chain_delay: 0.1
skill1_chain_next: none
skill1_delay_max: 5.0
skill1_delay_min: 2.0
skill1_enabled: false
skill1_hp_max: 100
skill1_hp_min: 0
skill1_mode: delay
skill1_pos:
- 1478
- 1308
- 64
- 65
skill1_priority: 1
skill1_resource_max: 100
skill1_resource_min: 0
skill2: '2'
skill2_always_available: false
skill2_always_hold: true
skill2_cal:
  pixel1_brightness: 175.7
  pixel1_x: 1598
  pixel1_y: 1320
  pixel2_brightness: 123.7
  pixel2_x: 1601
  pixel2_y: 1329
skill2_chain_delay: 0.1
skill2_chain_next: none
skill2_delay_max: 0.0
skill2_delay_min: 0.0
skill2_enabled: true
skill2_hp_max: 100
skill2_hp_min: 0
skill2_mode: ready
skill2_pos:
- 1557
- 1307
- 72
- 65
skill2_priority: 6
skill2_resource_max: 100
skill2_resource_min: 0
skill3: '3'
skill3_always_available: false
skill3_always_hold: true
skill3_cal:
  pixel1_brightness: 209.7
  pixel1_x: 1680
  pixel1_y: 1315
  pixel2_brightness: 109.0
  pixel2_x: 1685
  pixel2_y: 1319
skill3_chain_delay: 0.1
skill3_chain_next: none
skill3_delay_max: 0.0
skill3_delay_min: 0.0
skill3_enabled: true
skill3_hp_max: 100
skill3_hp_min: 0
skill3_mode: ready
skill3_pos:
- 1646
- 1309
- 64
- 63
skill3_priority: 2
skill3_resource_max: 100
skill3_resource_min: 0
skill4: '4'
skill4_always_available: false
skill4_always_hold: true
skill4_cal:
  pixel1_brightness: 201.0
  pixel1_x: 1764
  pixel1_y: 1317
  pixel2_brightness: 174.7
  pixel2_x: 1772
  pixel2_y: 1320
skill4_chain_delay: 0.0
skill4_chain_next: none
skill4_delay_max: 1.5
skill4_delay_min: 0.5
skill4_enabled: true
skill4_hp_max: 100
skill4_hp_min: 0
skill4_mode: delay
skill4_pos:
- 1731
- 1309
- 65
- 63
skill4_priority: 1
skill4_resource_max: 100
skill4_resource_min: 0
skill5: e
skill5_always_available: false
skill5_always_hold: true
skill5_cal:
  pixel1_brightness: 137.3
  pixel1_x: 1850
  pixel1_y: 1318
  pixel2_brightness: 178.3
  pixel2_x: 1854
  pixel2_y: 1332
skill5_chain_delay: 0.1
skill5_chain_next: none
skill5_delay_max: 0.0
skill5_delay_min: 0.0
skill5_enabled: true
skill5_hp_max: 100
skill5_hp_min: 0
skill5_mode: ready
skill5_pos:
- 1812
- 1307
- 66
- 65
skill5_priority: 2
skill5_resource_max: 100
skill5_resource_min: 0
skill6: rightclick
skill6_always_available: true
skill6_always_hold: true
skill6_cal:
  pixel1_brightness: 125.0
  pixel1_x: 1931
  pixel1_y: 1317
  pixel2_brightness: 157.0
  pixel2_x: 1935
  pixel2_y: 1320
skill6_chain_delay: 0.1
skill6_chain_next: none
skill6_delay_max: 0.0
skill6_delay_min: 0.0
skill6_enabled: false
skill6_hp_max: 100
skill6_hp_min: 0
skill6_mode: hold
skill6_pos:
- 1899
- 1308
- 63
- 65
skill6_priority: 6
skill6_resource_max: 100
skill6_resource_min: 0
